### ISSUE TITLE
The JQuery Dependency of Yunba Javascript SDK

### ISSUE THREAD

**Issue by rollandlee** [yunba/yunba-javascript-sdk#7]
JQuery is not that popular if quite a lot of apps are built on Cordova/Angular or React. Besides, I cannot found that JQuery works quite a lot in the file

the only thing that i found should be something like $.query('sessionid')

Can we remove the JQuery dependency

and in my opinion, the socket io dependency can be removed also.

**Comment by wuyingfengsui** [comment]
Do you have any recommendations about stringquery operate without JQuery?

**Comment by rollandlee** [comment]
var sessionid = location.search.match(new RegExp("[\?\&]sessionid=([^\&]+)", "i"));

**Comment by wuyingfengsui** [comment]
set/remove? can you pull request about it?

**Comment by rollandlee** [comment]
sorry, i did't notice that we need get/set func too.
here's a link with some comprehensive functions for querystring
http://www.cnblogs.com/mingda/archive/2010/01/17/1649952.html

**Comment by wuyingfengsui** [comment]
https://github.com/yunba/yunba-javascript-sdk/commit/16b318808593ae30c5671ae779e1b533f7478239
